[package]
name = "oakeyc_rust_book_art"
version = "0.1.0"
authors = ["Courtney Oka <oakeyc@github.com>"]
edition = "2018"
license = "MIT"
description = "chapter 14 about crates"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
